In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)

df = pd.read_csv(r'analysis_df.csv')
df.head()

,type,latitude,longitude,lease_type,gym,lift,swimming_pool,negotiable,furnishing,parking,property_size,property_age,bathroom,facing,cup_board,floor,total_floor,water_supply,building_type,balconies,rent
0,BHK2,12.929557,77.672280,ANYONE,0,1,0,1,SEMI_FURNISHED,BOTH,1400,4,2,NE,2,3,4,CORPORATION,AP,2,22000
1,BHK3,12.982870,80.262012,FAMILY,0,1,0,0,SEMI_FURNISHED,BOTH,1350,6,3,E,3,1,5,CORPORATION,AP,3,28000
2,BHK1,12.955991,77.531634,FAMILY,0,0,0,1,SEMI_FURNISHED,TWO_WHEELER,600,3,1,E,1,1,2,CORPORATION,IH,0,8000
3,BHK3,12.963903,77.649446,FAMILY,0,0,0,1,SEMI_FURNISHED,BOTH,1500,15,3,E,4,0,0,CORPORATION,IH,1,45000
4,BHK3,12.967144,77.750662,ANYONE,1,1,1,1,FULLY_FURNISHED,BOTH,1895,5,3,NE,5,3,9,CORPORATION,AP,3,32000

In [2]:
new_df = df.drop(['latitude', 'longitude'], axis = 1)
new_df.head()

,type,lease_type,gym,lift,swimming_pool,negotiable,furnishing,parking,property_size,property_age,bathroom,facing,cup_board,floor,total_floor,water_supply,building_type,balconies,rent
0,BHK2,ANYONE,0,1,0,1,SEMI_FURNISHED,BOTH,1400,4,2,NE,2,3,4,CORPORATION,AP,2,22000
1,BHK3,FAMILY,0,1,0,0,SEMI_FURNISHED,BOTH,1350,6,3,E,3,1,5,CORPORATION,AP,3,28000
2,BHK1,FAMILY,0,0,0,1,SEMI_FURNISHED,TWO_WHEELER,600,3,1,E,1,1,2,CORPORATION,IH,0,8000
3,BHK3,FAMILY,0,0,0,1,SEMI_FURNISHED,BOTH,1500,15,3,E,4,0,0,CORPORATION,IH,1,45000
4,BHK3,ANYONE,1,1,1,1,FULLY_FURNISHED,BOTH,1895,5,3,NE,5,3,9,CORPORATION,AP,3,32000

##### **Encoding categorical Features**

In [3]:
category_df = new_df[['type','lease_type','furnishing','parking','facing','water_supply','building_type']]
category_df.head()

,type,lease_type,furnishing,parking,facing,water_supply,building_type
0,BHK2,ANYONE,SEMI_FURNISHED,BOTH,NE,CORPORATION,AP
1,BHK3,FAMILY,SEMI_FURNISHED,BOTH,E,CORPORATION,AP
2,BHK1,FAMILY,SEMI_FURNISHED,TWO_WHEELER,E,CORPORATION,IH
3,BHK3,FAMILY,SEMI_FURNISHED,BOTH,E,CORPORATION,IH
4,BHK3,ANYONE,FULLY_FURNISHED,BOTH,NE,CORPORATION,AP

In [4]:
for i in category_df.columns:
    print(f'The value counts of {i} : {category_df[i].value_counts()}')
    print('__________________________________________________________')

The value counts of type : type
BHK2        9776
BHK3        3583
BHK1        2982
RK1          448
BHK4         199
BHK4PLUS      24
Name: count, dtype: int64
__________________________________________________________
The value counts of lease_type : lease_type
FAMILY      8439
ANYONE      8011
BACHELOR     514
COMPANY       48
Name: count, dtype: int64
__________________________________________________________
The value counts of furnishing : furnishing
SEMI_FURNISHED     14773
NOT_FURNISHED       1242
FULLY_FURNISHED      997
Name: count, dtype: int64
__________________________________________________________
The value counts of parking : parking
BOTH            8601
TWO_WHEELER     6264
FOUR_WHEELER    1211
NONE             936
Name: count, dtype: int64
__________________________________________________________
The value counts of facing : facing
E     7885
N     4877
W     2142
S     1097
NE     663
SE     175
NW     123
SW      50
Name: count, dtype: int64
__________________________________________________________
The value counts of water_supply : water_supply
CORPORATION    14752
BOREWELL        2260
Name: count, dtype: int64
__________________________________________________________
The value counts of building_type : building_type
IF    8019
AP    6858
IH    2121
GC      14
Name: count, dtype: int64
__________________________________________________________

##### **Feature selection**

In [5]:
corr_df = new_df.corr()

import plotly.express as px

fig = px.imshow(corr_df, text_auto = True)
fig.update_layout(width = 1500, height = 800)
fig.show()

ValueError: could not convert string to float: 'BHK2'